# Simulation Scenarios
simulate: 'echo'

# Corruptions Attribute
NOISE_SNRS: 30 #[40, 30, 20, 10, 0]
ADV_SNRS: [50, 40, 30, 20, 10]
RESAMPLING_FACTORS: 0.75 #[1, 0.75, 0.5, 0.25, 0.125]
GAIN_FACTORS: 10 #[0, 10, 20, 30, 40]
ECHO_DELAYS: 500 #[0, 125, 250, 500, 1000]
LOWPASS_FREQS: 8000 #[8000, 4000, 2833, 1666, 500]
HIGHPASS_FREQS: 1500 #[0, 875, 1500, 2125, 3000]

# Dataset Params. 
sample_rate: 16000
dataset_name: "libri_speech"


# Directories Info.
output_dir: "./output_dir/"
noise_dir: "./noise_data/"
model_dir: "./" # cache_directory "location of model's checkpoints"
data_cache_dir: "" # cache_directory "location of data"
tts_dir: "/u/mbaali/CosyVoice/" # ur tts directory
tts_type: "zero_shot" # zero_shot OR cross-lingual
tts_lang: 'en'

# Checkpoint for MFA Conformer
mfa_ckpt: 'model.ckpt'
