# Corruptions Attribute

device: cuda
threshold: 0.0

attack:
  epsilon: 0.1
  confidence: 0.0
  max_iter: 1000       # Decrease for faster inference
  stop_early_iter: 100 # Decrease for faster inference
  samples_per_draw_batch_size: 2 # Do not change!
  threshold: 0.0 # Should be the same as above
