# Corruptions Attribute
model: !PLACEHOLDER # Create model under attack here

targeted: False # Whether to use the trial label as a target or as the class to be "opposed"
eps: 0.1        # Used in all attacks except C&W variants
max_iter: 100   # Not used in FGSM
confidence: 0.5 # Only used in C&W attacks

params:
  targeted: !ref <targeted>
  eps: !ref <eps>
  confidence: !ref <confidence>
  max_iter: !ref <max_iter>

